# Generated by Django 5.0.7 on 2024-08-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customer/')),
                ('slug', models.SlugField(blank=True, default=1, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',

                'ordering': ('first_name', 'last_name', 'phone'),
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
