# Generated by Django 5.0.7 on 2024-08-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options_alter_customer_slug'),
    ]

    operations = [
    ]
