# Generated by Django 5.0.7 on 2024-08-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20240813_1649'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_customer',
        ),
    ]
