# Generated by Django 5.1 on 2024-08-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
